index_route:
  path: '/'
  action: 'Front:index'
  method: 'get'

page_route:
  path: '/page/{page}'
  action: 'Front:page'

login_route:
  path: '/login'
  action: 'Front:login'
  method: 'get'

login_route_check:
  path: '/login'
  action: 'Front:login'
  method: 'post'

register_route:
  path: '/register'
  action: 'Front:register'
  method: 'post'

register_route_get:
  path: '/register'
  action: 'Front:register'
  method: 'get'

log_out:
  path: '/log_out'
  action: 'Front:logOut'