admin_route:
  path: '/admin'
  action: 'Admin:index'

admin_pages_route:
  path: '/admin/pages'
  action: 'Admin:pages'

admin_page_route:
  path: '/admin/page[/{id:\d+}]'
  action: 'Admin:page'
  method: 'get'

admin_page_route_save:
  path: '/admin/page[/{id:\d+}]'
  action: 'Admin:page'
  method: 'post'

admin_page_delete_route:
  path: '/admin/page/delete'
  action: 'Admin:pageDelete'
  method: 'post'

admin_users_route:
  path: '/admin/users'
  action: 'Admin:users'

admin_user_route:
  path: '/admin/user[/{id:\d+}]'
  action: 'Admin:user'
  method: 'get'

admin_user_route_save:
  path: '/admin/user[/{id:\d+}]'
  action: 'Admin:user'
  method: 'post'

admin_user_delete_route:
  path: '/admin/user/delete'
  action: 'Admin:userDelete'
  method: 'post'