admin_route:
  path: '/admin'
  action: 'Admin:index'

admin_pages_route:
  path: '/admin/pages'
  action: 'Admin:pages'

admin_page_route:
  path: '/admin/page[/{id:\d+}]'
  action: 'Admin:page'

admin_page_delete_route:
  path: '/admin/page/{id:\d+}/delete'
  action: 'Admin:pageDelete'